### ISSUE TITLE
Error Displaying PartitionTable with Int Partition Column

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/web-client-ui#1482] opened 2023-09-05 17:02 UTC
**Description**

If the first partition column on a table is an Int column, then the UI fails to show an initial view of that table. 

**Steps to reproduce**

```groovy
import io.deephaven.engine.util.TableTools
import io.deephaven.parquet.table.ParquetTools

// write a partition table with an int partition column
def part = TableTools.emptyTable(4).update("II = ii")
ParquetTools.writeTable(part, "/tmp/pt-test/intCol=0/part.parquet")
ParquetTools.writeTable(part, "/tmp/pt-test/intCol=1/part.parquet")

// load the partition table
partition_table = ParquetTools.readTable("/tmp/pt-test")

// dump the metadata to the console to see that it is indeed an `intCol`
TableTools.show(partition_table.meta())
```

**Expected results**
That the UI would grab the "most recent" partition and display the partition table.

**Actual results**

The UI sends a string filter to the backend, which fails as it is not the right type. 
<img width="1027" alt="Screenshot 2023-09-05 at 10 59 10 AM" src="https://github.com/deephaven/web-client-ui/assets/1030443/f404d0c4-a940-442d-bde2-842b702f3d83">

This is the server side error:
```
-7241-4086-aaf3-4b7673abc6f5' java.lang.IllegalArgumentException: Failed to convert literal value <"1"> for column "intCol" of type int
	at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:155)
	at io.deephaven.engine.table.impl.PartitionAwareSourceTable.whereImpl(PartitionAwareSourceTable.java:288)
	at io.deephaven.engine.table.impl.PartitionAwareSourceTable.where(PartitionAwareSourceTable.java:272)
	at io.deephaven.engine.table.impl.PartitionAwareSourceTable.where(PartitionAwareSourceTable.java:35)
	at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:57)
	at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:30)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:689)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:541)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:921)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NumberFormatException: For input string: ""1""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.deephaven.engine.table.impl.select.MatchFilter$ColumnTypeConvertorFactory$3.convertStringLiteral(MatchFilter.java:225)
	at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:152)
	... 15 more
```

**Comment by dsmmcken** [comment] 2023-09-05 17:15
Duplicate of #1441

**Closed by dsmmcken** 2023-09-05 17:15 UTC
Labels: bug, triage
