### ISSUE TITLE
The User Interface's File Explorer Appears Broken in Embedded Server on Windows

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/web-client-ui#1836] opened 2024-02-27 01:50 UTC
A community user reports not being able to create directories or save files.

One such error: "Invalid filename provided: \Untitled-0.py"

They are launching the community worker via:
```python
from deephaven_server import Server
s = Server(port=10000, jvm_args=["-Xmx4g", "-Dauthentication.psk=password"]).start()
```

Adding `-Dstorage.path=/path/for/storage` does not appear to work.

**Comment by mofojed** [comment] 2024-02-27 02:50
Duplicate of https://github.com/deephaven/deephaven-core/issues/5068

**Closed by mofojed** 2024-02-27 02:50 UTC
Labels: bug
