### ISSUE TITLE
Drop down filter doesn't work

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#190] opened 2021-09-08 14:19 UTC
**Description**

Attempting to use the drop down filter on a string column doesn't work.

**Steps to reproduce**
1. Create a table
2. Copy that table, and select distinct on a string column
3. Add a dropdown filter panel
4. Set the source to be the distinct string column
5. Set the target to be the original tables column of the same name
6. Use the dropdown filter to attempt to fitler the table

**Expected results**

The table is filtered to the selected value.

**Actual results**

![image](https://user-images.githubusercontent.com/1576283/132526642-f5f76d77-c085-42ba-8be4-8d21ced42951.png)

```
caused by:
java.lang.IllegalArgumentException: String literal not enclosed in quotes ("batsy")
```

**Comment by dsmmcken** [comment] 2021-09-08 14:23
Actually, attempting to filter any string doesnt work in quick filter bar either

**Comment by dsmmcken** [comment] 2021-09-08 14:29
More notes: Right clicking filter by text does seem to work. So not sure what's going on here.

**Comment by mofojed** [comment] 2021-09-08 18:36
The error is with any string filters, some errors on the server side. Created a table with some string columns:
```
from deephaven import TableTools
t = TableTools.emptyTable(100).update("A=i", "B=`Hello`")
```

Tried to add a filter with quickfilters to column B filtering on 'Hello':

```
grpc-proxy_1  | time="2021-09-08T18:34:54Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Release grpc.service=io.deephaven.proto.backplane.grpc.SessionService grpc.start_time="2021-09-08T18:34:54Z" grpc.time_ms=2.024 span.kind=server system=grpc
grpc-api_1    | 2021-09-08T18:34:54.884Z | heduler-Concurrent-1 | ERROR | i.d.g.s.SessionState      | Internal Error '8f40da47-6294-436e-8213-0460f905df4b' java.lang.IllegalArgumentException: Failed to convert literal value <hello> for column "B" of type java.lang.String
grpc-api_1    |         at io.deephaven.db.v2.select.MatchFilter.init(MatchFilter.java:140)
grpc-api_1    |         at io.deephaven.db.v2.QueryTable.lambda$where$41(QueryTable.java:1021)
grpc-api_1    |         at io.deephaven.db.tables.utils.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:483)
grpc-api_1    |         at io.deephaven.db.v2.QueryTable.where(QueryTable.java:991)
grpc-api_1    |         at io.deephaven.grpc_api.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:85)
grpc-api_1    |         at io.deephaven.grpc_api.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:16)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:450)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$null$6(TableServiceGrpcImpl.java:319)
grpc-api_1    |         at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:825)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    | caused by:
grpc-api_1    | java.lang.IllegalArgumentException: String literal not enclosed in quotes ("hello")
grpc-api_1    |         at io.deephaven.db.v2.select.MatchFilter$ColumnTypeConvertorFactory$9.convertStringLiteral(MatchFilter.java:264)
grpc-api_1    |         at io.deephaven.db.v2.select.MatchFilter.init(MatchFilter.java:137)
grpc-api_1    |         at io.deephaven.db.v2.QueryTable.lambda$where$41(QueryTable.java:1021)
grpc-api_1    |         at io.deephaven.db.tables.utils.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:483)
grpc-api_1    |         at io.deephaven.db.v2.QueryTable.where(QueryTable.java:991)
grpc-api_1    |         at io.deephaven.grpc_api.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:85)
grpc-api_1    |         at io.deephaven.grpc_api.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:16)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:450)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$null$6(TableServiceGrpcImpl.java:319)
grpc-api_1    |         at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:825)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    | 
grpc-proxy_1  | time="2021-09-08T18:34:54Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Batch grpc.service=io.deephaven.proto.backplane.grpc.TableService grpc.start_time="2021-09-08T18:34:54Z" grpc.time_ms=3.079 span.kind=server system=grpc
grpc-proxy_1  | time="2021-09-08T18:34:55Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Batch grpc.service=io.deephaven.proto.backplane.grpc.TableService grpc.start_time="2021-09-08T18:34:55Z" grpc.time_ms=2.379 span.kind=server system=grpc
grpc-api_1    | 2021-09-08T18:34:55.135Z | heduler-Concurrent-2 |  INFO | i.d.g.a.ArrowFlightUtil   | DoExchangeMarshaller{2bfe3c}: processing initial subscription
grpc-api_1    | 2021-09-08T18:34:55.136Z | heduler-Concurrent-2 |  INFO | .b.BarrageMessageProducer | BarrageMessageProducer(e818c89): Sub{524f01ac}: subbing to columns {0-1}
grpc-api_1    | 2021-09-08T18:34:55.136Z | heduler-Concurrent-2 |  INFO | .b.BarrageMessageProducer | BarrageMessageProducer(e818c89): Sub{524f01ac}: scheduling update immediately, for initial snapshot.
grpc-api_1    | 2021-09-08T18:34:55.136Z | heduler-Concurrent-4 |  INFO | .d.v.InstrumentedListener | 243371145: Snapshot candidate step=381, rows={0-28}/{0-28}, cols={0-1}, usePrev=false
envoy_1       | [2021-09-08T18:34:46.944Z] "GET /io.deephaven.proto.backplane.grpc.SessionService/RefreshSessionToken HTTP/1.1" 101 UC 180 261 6 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0" "8d61fad7-911d-4c2e-ba00-3bc7d404bc3c" "localhost:10000" "172.18.0.4:8080"
envoy_1       | [2021-09-08T18:34:48.262Z] "GET /io.deephaven.proto.backplane.grpc.SessionService/RefreshSessionToken HTTP/1.1" 101 UC 180 261 3 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0" "7c8969d5-d947-44a0-a7ab-10c1eaad9fc2" "localhost:10000" "172.18.0.4:8080"
envoy_1       | [2021-
```

**Comment by mofojed** [comment] 2021-09-08 18:37
It works if the quick filter value is surrounded in quotes. I think somewhere in the API it's supposed to be wrapping the value in quotes and it is not, I'll distill down to a basic example.

**Comment by mofojed** [comment] 2021-09-08 18:48
Looks to be limited to `eqIgnoreCase`, and can reproduce from one of the JS API example pages in the console by running:
```
var result = await ide.runCode('from deephaven.TableTools import emptyTable\nt = emptyTable(10).update("A=`Hello`")');
var table = await ide.getTable('t');
table.applyFilter([table.columns[0].filter().eqIgnoreCase(dh.FilterValue.ofString('Hello'))])
```

Doing `.eq(...)` works fine. Will investigate.

**Comment by mofojed** [comment] 2021-09-08 19:18
Looks like it may be related to https://github.com/deephaven/deephaven-core/issues/733

**Comment by mofojed** [comment] 2021-09-13 13:51
Fixed by https://github.com/deephaven/deephaven-core/pull/1229

**Closed by mofojed** 2021-09-13 13:51 UTC
Labels: bug, blocker
